---
all:
  children:
    development:
      hosts:
        ringtail.local:
        indri:
    gaming:
      hosts:
        ringtail.local:
    workmachines:
      hosts:
        ringtail.local:
        indri:
