---
all:
  children:
    development:
      hosts:
        ringtail:
        indri.local:
    gaming:
      hosts:
        ringtail:
    workmachines:
      hosts:
        ringtail:
        indri.local:
