---
all:
  children:
    development:
      hosts:
        ringtail:
        ObvsMBP219:
    gaming:
      hosts:
        ringtail:
    osx:
      hosts:
        ObvsMBP219:
    work:
      hosts:
        ObvsMBP219:
