---
neovim_version: 'v0.4.3'  # as of 2019-12-21, 0.5 is about to come out
tmux_version: '3.0a'
fisher_version: '2.13.0'  # NB: this is quite out of date. But I don't care.
pyenv_version: 'v1.2.15'  # latest release as of 2019-12-21
pyenv_virtualenv_version: 'v1.1.5'
pyenv_global_version: '3.7.3'

ansible_check_mode: false  # No idea wtf is going on with this

code_pen_dir: "{{ ansible_env.HOME }}/code"
work_code_dir: "{{ code_pen_dir }}/work"
nonwork_code_dir: "{{ code_pen_dir }}/personal"
user_bin_dir: "{{ ansible_env.HOME }}/bin"
fish_bin: /usr/bin/fish
gem_bin: /usr/bin/gem
