---

- name: Install fish shell
  become: yes
  apt: name=fish state=present

- name: change shell to fish
  become: yes
  user:
    name: '{{ansible_user_id}}'
    shell: /usr/bin/fish

# TODO - full user management


- include: apt.yml
