#!/usr/bin/env bash
#
# user-vpn
# blume.erich@gmail.com
# helper script to load a .ovpn provile bundle (OpenVPN)
# Suggested by Bailey Stoner


profile=$1


usage() {
  printf "Usage: %s <profile>\n\nProfiles found:\n" $0 > /dev/stderr
  ls -1 ${HOME}/openvpn/*.ovpn | xargs -n 1 basename -s .ovpn 1>&2
  exit 1
}


[[ -z ${profile} ]] && usage

command -v openvpn 2>&1 > /dev/null || usage
  

exec sudo openvpn --config ${HOME}/openvpn/${profile}.ovpn
