---

- name: Set work code dir
  set_fact: work_dir="{{ansible_env.HOME}}/code/work"

- name: Create work dir
  file:
    path: work_dir
    state: directory

- name: Check out work projects
  git:
    repo: "git@github.com:Coffee-Meets-Bagel/{{ item }}.git"
    dest: "{{ work_dir }}/{{ item }}"
    update: no
  with_items:
    - Project-Vitamin
    - devops
    - CMBSchemas
    - postman
    - qa
    - ottobot
    - gitana
    - cmb-docker

# TODO - docker for OS X

- name: Install docker (Linux)
  when: ansible_os_family == "Debian"
  become: yes
  block:

    - name: Add docker apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add docker apt repo
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu disco stable"
        state: present

    - name: Install docker
      become: yes
      apt:
        state: latest
        name:
          - docker-ce

    # TODO: De-command these

    - name: Install docker-compose
      become: yes
      command: curl -L "https://github.com/docker/compose/releases/download/1.28.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

    - name: Mark docker-compose executable
      become: yes
      command: chmod +x /usr/local/bin/docker-compose

- name: Install VPN (Linux)
  when: ansible_os_family == "Debian"
  block:

    - name: Install openvpn
      become: yes
      apt:
        state: latest
        name:
          - openvpn
          - network-manager-openvpn

# This can probably be done with the 'npm' module, but I'm skeptical of it

- name: Install required global node packages
  command: "n exec latest npm install -g {{item}}"
  with_items:
    - gsts
