---

- name: Set work code dir
  set_fact: work_dir="{{ansible_env.HOME}}/code/work"

- name: Create work dir
  file:
    path: work_dir
    state: directory

- name: Check out work projects
  git:
    repo: "git@github.com:Coffee-Meets-Bagel/{{ item }}.git"
    dest: "{{ work_dir }}/{{ item }}"
    update: no
  with_items:
    - Project-Vitamin
    - PushService
    - feature-engine-db-client
    - CMBAndroid
    - CMBiOS
    - py-rabbitmq-client
    - etl-dw
    - feature-engine-consumer
    - CMBJupyter
    - DataCommon
    - devops
    - CMBSchemas
    - postman
    - qa
    - ottobot
    - gitana
    - cmb-docker
    - model-service

- name: Add work config to fish
  template:
    src: 002-work.fish.j2
    dest: "{{ ansible_env.HOME }}/.config/fish/conf.d/002-work.fish"
