---

- name: Install openvpn
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - openvpn
    - resolvconf

- name: Install the user-vpn vpn manager script
  copy:
    src: ../files/user-vpn
    dest: "{{ user_bin_dir }}/user-vpn"
    mode: "u=rx,g=rx,o=r"

- name: Create the openvpn profile folder
  file: path="{{ ansible_env.HOME }}/openvpn" state=directory

- name: Install the openvpn bundle profiles
  copy:
    src: ../files/erich.ovpn
    dest: "{{ ansible_env.HOME }}/openvpn/erich.ovpn"
    mode: "u=r,g=,o="

- name: Install the vpn password files
  copy:
    src: ../files/vpn.cred
    dest: "{{ ansible_env.HOME }}/openvpn/vpn.cred"
    mode: "u=r,g=,o="

- name: Install the openvpn_dns_hook
  copy:
    src: ../files/old_openvpn_hook.sh
    #  src: ../files/openvpn_dns_hook.sh
    dest: "{{ ansible_env.HOME }}/openvpn/openvpn_dns_hook.sh"
    mode: "u=rx,g=,o="  # It's not a secure file, but no reason to expose it anyway

- name: Create ssh config dir
  file: path="{{ ansible_env.HOME }}/.ssh" state=directory mode="u=rwx,g=,o="

- name: Set up ssh config
  copy:
    src: ../files/ssh.config
    dest: "{{ ansible_env.HOME }}/.ssh/config"
    mode: "u=r,g=,o=" 

- name: Check out professional projects
  git:
    repo: "git@github.com:patreon/{{ item }}.git"
    dest: "{{ work_code_dir}}/{{item}}"
    update: no  # We'll handle that in other ways
  with_items:
    - devx-frontend
    - populous
    - ansible
    - patreon_py
