---

- name: Remove tmux build folder
  file: path="{{ nonwork_code_dir }}/tmux/build" state=absent

- name: Clean tmux build artifacts
  command: make clean
  args:
    chdir: "{{ nonwork_code_dir }}/tmux"
  ignore_errors: true

- name: Configure tmux autogen
  command: sh autogen.sh
  args:
    chdir: "{{ nonwork_code_dir }}/tmux"

- name: Configure tmux
  command: "./configure"
  args:
    chdir: "{{ nonwork_code_dir }}/tmux"

- name: Build tmux (this may take a bit)
  command: "make -j 8"
  args:
    chdir: "{{ nonwork_code_dir }}/tmux"
