---

- name: Remove tmux build folder
  file: path="{{ nonwork_code_dir }}/tmux/build" state=absent

- name: Clean tmux build artifacts
  command: make clean
  args:
    chdir: "{{ nonwork_code_dir }}/tmux"
  ignore_errors: yes

- name: Delete pesky nightly tag from tmux repository (sheesh x2)
  command: git tag -d nightly
  args:
    chdir: "{{ nonwork_code_dir }}/tmux"
  ignore_errors: yes

- name: Configure tmux autogen
  command: sh autogen.sh
  args:
    chdir: "{{ nonwork_code_dir }}/tmux"

- name: Configure tmux
  command: "./configure"
  args:
    chdir: "{{ nonwork_code_dir }}/tmux"

- name: Build tmux (this may take a bit)
  command: "make -j 8"
  args:
    chdir: "{{ nonwork_code_dir }}/tmux"

- name: Link in tmux
  file:
    src: "{{ nonwork_code_dir }}/tmux/tmux"
    dest: "{{ user_bin_dir }}/tmux"
    state: link
    mode: u+x
