---

- name: Download the n installer script
  get_url:
    url: https://git.io/n-install
    dest: "{{ nonwork_code_dir }}/n-install.sh"
    mode: u=rwx,g=rx,o=rx

- name: Install n
  script: "{{ nonwork_code_dir }}/n-install.sh -q -n"
  register: n_install
  failed_when: n_install.rc != 0 and n_install.rc != 3  # 3: 'n already installed'

# TODO - use a pyenv-like system where I install a bunch of versions and target
# one globally. Instead, for now, just go to the next LTS.

- name: Install latest version of node via n
  command: n latest --preserve
