---

- name: Install essentials (Debian)
  become: yes
  when: ansible_os_family == "Debian"
  apt:
    state: present
    pkg:
      - build-essential
      - git

- name: Install essentials (OS X)
  when: ansible_os_family == "Darwin"
  homebrew:
    state: latest
    name:
      - git
      - coreutils
      - findutils
      - gnu-tar
      - gnu-sed
      - grep
