---

- name: Check out the pyenv code
  git:
    repo: git@github.com:pyenv/pyenv.git
    dest: "{{ nonwork_code_dir }}/pyenv"
    version: "{{ pyenv_version }}"
  register: pyenv_git

- name: Check out the pyenv-virtualenv plugin
  git:
    repo: git@github.com:pyenv/pyenv-virtualenv.git
    dest: "{{ nonwork_code_dir }}/pyenv/plugins/pyenv-virtualenv"
    version: "{{ pyenv_virtualenv_version }}"
  register: pyenv_virtualenv_git

- name: "Gather info on installed versions of python"
  when: pyenv_git.changed or pyenv_virtualenv_git.changed
  command: "{{ nonwork_code_dir }}/pyenv/bin/pyenv versions"
  register: pyenv_versions_check

- name: Install python versions in to pyenv
  when: pyenv_versions_check.changed and item in pyenv_versions_check.stdout
  command: "{{ nonwork_code_dir }}/pyenv/bin/pyenv install {{ item }}"
  with_items:
    - "2.7.15"
    - "3.7.0"
    - "3.6.6"
    - "pypy3.5-6.0.0"

- name: Check which version of pyenv is global
  command: "{{ nonwork_code_dir }}/pyenv/bin/pyenv global"
  register: pyenv_global_check
  changed_when: false

- name: Install the global python version
  when: 
    - pyenv_global_check.stdout == 'system'
  command: "{{ nonwork_code_dir }}/pyenv/bin/pyenv install {{ pyenv_global_version }}"
  register: pyenv_global_install
  ignore_errors: pyenv_global_install.stderr and pyenv_global_install.stderr.endswith('already exists')

- name: Set the global python version
  when: 
    - pyenv_global_check.stdout == 'system'
  command: "{{ nonwork_code_dir }}/pyenv/bin/pyenv global {{ pyenv_global_version }}"
