---

- name: Install neovim (Debian)
  when: ansible_os_family == "Debian"
  block:
    - name: Install neovim dependencies
      block:
        - name: 
    - name: Clone neovim repository
      git: 
        repo: 'git@github.com:neovim/neovim.git'
        dest: {{ NONWORK_CODE_DIR }}
        version: 'v0.3.1'
    - name: "Build, configure, and install neovim"
      chdir: "{{ NONWORK_CODE_DIR }}/neovim"
      block:
      - name: Set neovim install path for builder
        command: make CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX={{ user_bin_dir }}/"
      - name: Build neovim
        command: make CMAKE_BUILD_TYPE=RelWithDebInfo
        chdir: "{{ NONWORK_CODE_DIR }}/neovim"
      - name: Install neovim
        command: make install
        chdir: "{{ NONWORK_CODE_DIR }}/neovim"
      - name: Install neovim config
        # TODO
      - name: Install neovim plugins
        # TODO
