---

- name: Install essentials (Debian)
  become: yes
  when: ansible_os_family == "Debian"
  apt:
    state: present
    pkg:
      - build-essential
      - git
      - python3
      - software-properties-common

      # The following are needed for scipi
      # (https://github.com/scipy/scipy/issues/9005)
      - gfortran
      - libopenblas-dev
      - liblapack-dev
- name: Install essentials (OS X)
  when: ansible_os_family == "Darwin"
  homebrew:
    state: latest
    name:
      - git
      - coreutils
      - findutils
      - gnu-tar
      - gnu-sed
      - grep
      - ripgrep

- name: Check out Z (shell frecency file finder)
  git:
    repo: 'git@github.com:rupa/z'
    dest: "{{ nonwork_code_dir }}/z_file_finder"

