---

- name: Install essentials (Debian)
  become: yes
  when: ansible_os_family == "Debian"
  apt: name="{{item}}" state=present
  with_items:
    - build-essential
    - tmux
    - git
    - libz-dev
