---

- name: Install docutils (needed for ctags)
  command: "fish -c \"source ({{ nonwork_code_dir }}/pyenv/bin/pyenv init -|psub); and pip install -U {{ item }}\""
  with_items:
    - docutils

- name: Checkout universal-ctags
  git:
    repo: "git@github.com:universal-ctags/ctags.git"
    dest: "{{ nonwork_code_dir }}/ctags"
  register: checkout_ctags

- name: (Re)build ctags autotools conf
  when: checkout_ctags.changed
  command: "./autogen.sh"
  args:
    chdir: "{{ nonwork_code_dir }}/ctags"

- name: (Re)configure ctags
  when: checkout_ctags.changed
  command: "./configure --prefix={{ ansible_env.HOME }}"
  args:
    chdir: "{{ nonwork_code_dir }}/ctags"

- name: (Re)make ctags
  when: checkout_ctags.changed
  command: "make"
  args:
    chdir: "{{ nonwork_code_dir }}/ctags"

- name: (Re)install ctags
  when: checkout_ctags.changed
  command: "make install"
  args:
    chdir: "{{ nonwork_code_dir }}/ctags"
