---

- name: Install fish shell (Debian)
  when: ansible_os_family == "Debian"
  become: yes
  apt: name=fish state=latest

- block:
    - name: Install fish shell (OS X)
      when: ansible_os_family == "Darwin"
      homebrew: name=fish state=latest

    - name: Checking /etc/shells
      shell: "grep '^{{ fish_bin }}$' /etc/shells"
      register: osx_login_shell_exists_in_etc_shells
      changed_when: false
      failed_when: osx_login_shell_exists_in_etc_shells.rc not in [0, 1]

    - name: Appending /etc/shells
      lineinfile: dest=/etc/shells line={{ fish_bin }} state=present owner=root group=wheel mode=0644
      become: True
      when: osx_login_shell_exists_in_etc_shells.rc == 1

  when: ansible_os_family == "Darwin"

- name: change shell to fish
  become: yes
  user:
    name: '{{ansible_user_id}}'
    shell: '{{ fish_bin }}'
  register: shell_change

- fail:
    msg: "Your shell has changed, please create a new login shell (log out and log in)"
  when: shell_change.changed

- name: create fish config folders
  file: name="{{ ansible_env.HOME }}/.config/fish/{{ item  }}"  state=directory
  with_items:
    - completions
    - conf.d
    - functions

- name: install fish config
  template:
    dest: "{{ ansible_env.HOME }}/.config/fish/config.fish"
    src: config.fish.j2

- name: create fish env config
  template:
    src: 000-env.fish.j2
    dest: "{{ ansible_env.HOME }}/.config/fish/conf.d/000-env.fish"

- name: create fish OS X specific config
  when: ansible_os_family == "Darwin"
  template:
    src: 001-homebrew.fish.j2
    dest: "{{ ansible_env.HOME }}/.config/fish/conf.d/001-homebrew.fish"

- name: create fisher folder
  file:
    name: "{{ ansible_env.HOME }}/.config/fish/functions"
    state: directory

- name: install fisher
  git:
    repo: "git@github.com:jorgebucaran/fisher.git"
    dest: "{{ nonwork_code_dir }}/fisher"
    version: "{{ fisher_version }}"

- name: link fisher to fish functions
  file:
    src: "{{ nonwork_code_dir }}/fisher/fisher.fish"
    dest: "{{ ansible_env.HOME }}/.config/fish/functions/fisher.fish"
    state: link

- name: create fishfile
  lineinfile:
    create: yes
    line: "{{ item }}"
    state: present
    path: "{{ ansible_env.HOME}}/.config/fish/fishfile"
  with_items:
    - jethrokuan/z
    - fishpkg/fish-prompt-metro
    - danhper/fish-ssh-agent
  register: fishfile_change

- name: initialize fisherman plugins
  command: "fish -c fisher"
  when: fishfile_change.changed
  register: fisher_plugins_result
  changed_when:
    - fisher_plugins_result.stdout
    - not fisher_plugins_result.stdout.starts_with('No plugins to install')

# Powerline Fonts: this is to support metro, and it requires patching fonts
- name: Install powerline patched fonts (for metro fish prompt) (Debian only)
  become: yes
  apt: name=fonts-powerline state=latest
  when: ansible_os_family == "Debian"

- name: Create fonts directory
  when: ansible_os_family == "Darwin"
  file: path="{{ ansible_env.HOME }}/Library/Fonts" state=directory mode=u+rwx
  # This technically works on Linux too, maybe switch to only this?
- name: Install powerline patched fonts (OS X only)
  when: ansible_os_family == "Darwin"
  block:
    - name: Check out fonts
      git:
        repo: 'git@github.com:powerline/fonts.git'
        dest: "{{ nonwork_code_dir }}/powerline-fonts"
        version: HEAD
      register: fonts_git
    - name: Install fonts
      command: "{{ nonwork_code_dir}}/powerline-fonts/install.sh"
      when: fonts_git.changed
