---

- name: Install neovim dependencies (OS X)
  when: ansible_os_family == "Darwin"
  homebrew: name="{{ packages }}" state=latest
  vars:
    packages:
      - libxml2

- name: Install docutils (needed for ctags)
  command: "pip install -U docutils"
  register: docutils_result
  changed_when: "'Requirement already up-to-date' not in docutils_result.stdout"

- name: Install libxml (OS X)
  when: ansible_os_family == "Darwin"
  homebrew: name="libxml2" state="latest"
  # See also: https://github.com/mitmproxy/mitmproxy/issues/68#issuecomment-427751589

- name: Checkout universal-ctags
  git:
    repo: "git@github.com:universal-ctags/ctags.git"
    dest: "{{ nonwork_code_dir }}/ctags"
  register: checkout_ctags

- name: (Re)build ctags autotools conf
  when: checkout_ctags.changed
  command: "./autogen.sh"
  args:
    chdir: "{{ nonwork_code_dir }}/ctags"

- name: (Re)configure ctags
  when: checkout_ctags.changed
  command: "./configure --prefix={{ ansible_env.HOME }}"
  args:
    chdir: "{{ nonwork_code_dir }}/ctags"

- name: (Re)make ctags
  when: checkout_ctags.changed
  command: "make"
  args:
    chdir: "{{ nonwork_code_dir }}/ctags"

- name: (Re)install ctags
  when: checkout_ctags.changed
  command: "make install"
  args:
    chdir: "{{ nonwork_code_dir }}/ctags"

- name: Install ctags global config
  template: src="ctagsrc.j2" dest="{{ ansible_env.HOME }}/.ctags"
