---

- name: Install fish shell
  become: yes
  apt: name=fish state=present

- name: change shell to fish
  become: yes
  user:
    name: '{{ansible_user_id}}'
    shell: /usr/bin/fish

- name: install fish config
  template:
    src: config.fish.j2
    dest: "{{ ansible_env.HOME }}/.config/fish/config.fish"

- name: create fish config folders
  file: name="{{ ansible_env.HOME }}/.config/fish/{{ item  }}"  state=directory
  with_items:
    - completions 
    - conf.d
    - functions

- name: create fish env config
  template:
    src: 000-env.fish.j2
    dest: "{{ ansible_env.HOME }}/.config/fish/conf.d/000-env.fish"

- name: create fisher folder
  file:
    name: "{{ ansible_env.HOME }}/.config/fish/functions"
    state: directory

- name: install fisher
  git:
    repo: "git@github.com:jorgebucaran/fisher.git"
    dest: "{{ nonwork_code_dir }}/fisher"
    version: "{{ fisher_version }}"

- name: link fisher to fish functions
  file:
    src: "{{ nonwork_code_dir }}/fisher/fisher.fish"
    dest: "{{ ansible_env.HOME }}/.config/fish/functions/fisher.fish"
    state: link

# We could save ~1s if we parsed `fisher ls` first, but whatever :)
- name: Install fisher plugins
  command: "fish -c \"fisher {{ ' '.join(fisher_plugins) }}\""
  register: fisher_plugins_result
  changed_when:
    - fisher_plugins_result.stdout 
    - not fisher_plugins_result.stdout.starts_with('No plugins to install')
  vars:
    fisher_plugins:
      - z
