---

- include: hacks.yml

- include: install_essentials.yml
- include: code_pen.yml
- include: install_fish.yml
- include: install_vim.yml
- include: install_tmux.yml
- include: install_dotfiles.yml

- include: personal_dev.yml

- include: install_pyenv.yml

- include: packages.yml

- debug: msg="You should now run `exec fish` to reload your shell"
