---

- include: hacks.yml

- include: install_essentials.yml
- include: networking.yml
- include: install_ssh_keys.yml
- include: code_pen.yml
- include: install_fish.yml
- include: install_vim.yml
- include: install_tmux.yml
- include: install_dotfiles.yml

- include: personal_dev.yml
- include: professional_dev.yml

- include: work_vpn.yml

- include: install_pyenv.yml

- include: packages.yml
