---

- include: hacks.yml

# Disabled for now, todo
# - include: install_ansible.yml

- include: install_essentials.yml
- include: code_pen.yml
#- include: install_firefox.yml
- include: install_fish.yml
- include: install_pyenv.yml
- include: install_rbenv.yml
- include: install_vim.yml
- include: install_tmux.yml
- include: install_dotfiles.yml
- include: install_ctags.yml

# Tiling window managed (with OS X fallback)
- include: install_i3.yml
  when: ansible_os_family == "Debian"
- name: Install amethyst (OS X only)
  when: ansible_os_family == "Darwin"
  homebrew_cask: name="amethyst" state=upgraded
  register: amethyst_install
- debug:
    msg: "Amethyst requires accessibility options permissions, you must do this manually"
  when: amethyst_install.changed


- include: personal_dev.yml


- include: packages.yml

- debug: msg="You should now run `exec fish` to reload your shell"
