---

- name: Install user packages
  become: yes
  apt:
    state: present
    name:
      - firefox
      - chromium-browser
      - silversearcher-ag
      - snapd
      - xsel

- name: Check if slack needs to be installed
  command: "snap list slack"
  register: slack_installed

- name: Install slack snap with classic confinement
  become: yes
  command: "snap install slack --classic"
  when: not slack_installed
