---

# REMOVED - just contains fluxgui, which I dont think I'll need now
- name: Remove f.lux PPA
  become: yes
  apt_repository:
    repo: "ppa:nathan-renniewaldock/flux"
    state: absent

- name: Install user packages
  become: yes
  apt:
    state: present
    name:
      - firefox
      - chromium-browser
      - silversearcher-ag
      - snapd
      - xsel

- name: Install user snaps with classic confinement
  become: yes
  command: "snap install {{ item }} --classic"
  with_items:
    - slack
