---

- name: Install Debian Packages
  when: ansible_os_family == "Debian"
  block:
  - name: Install user packages
    become: yes
    apt:
      state: latest
      name:
        - chromium-browser
        - silversearcher-ag
        - snapd
        - xsel
        - blueman

- name: Install OS X Packages
  when: ansible_os_family == "Darwin"
  block:
  - name: Install user packages
    homebrew:
      path: /opt/homebrew/bin
      state: latest
      name:
        - the_silver_searcher
