---

- name: Check out personal projects
  git:
    repo: "git@github.com:eblume/{{ item }}.git"
    dest: "{{ nonwork_code_dir}}/{{item}}"
    update: no  # We'll handle that in other ways
  with_items:
    - hermes
    - envelop

- name: Install pip packages
  command: "fish -c \"source ({{ nonwork_code_dir }}/pyenv/bin/pyenv init -|psub); and pip install -U {{ item }}\""
  with_items:
    - pip
    - "pipenv==2018.7.1"  # Unpin after Nov 2018: https://github.com/pypa/pipenv/issues/2964
    - pdbpp
    - ipython
  register: pip_result
  changed_when: pip_result.rc == 0 and 'Successfully installed' in pip_result.stdout_lines[-1]
