---

- hosts: localhost
  connection: local  # default 'smart'
  roles:
    - common
  vars:
    neovim_version: 'v0.3.1'
    tmux_version: '2.7'
    vundle_version: 'v0.10.2'
    fisher_version: '2.13.0'
    pyenv_version: 'v1.2.7'  # latest release as of 04-Oct-18
    pyenv_virtualenv_version: 'v1.1.3'
    pyenv_global_version: '3.7.0'

    ansible_check_mode: false  # No idea wtf is going on with this
    code_pen_dir: "{{ ansible_env.HOME }}/code"
    work_code_dir: "{{ code_pen_dir }}/patreon"
    nonwork_code_dir: "{{ code_pen_dir }}/notreon"
    user_bin_dir: "{{ ansible_env.HOME }}/bin"
  
  # Conditional role application
  tasks:
    - include_role:
        name: work
      when: (ansible_hostname == 'shapeofwater') or
            (ansible_hostname == 'ringtail')
    - include_role:
        name: gaming
      when: ansible_hostname == 'ringtail'
